name: test

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    # runs-on: ubuntu-latest
    runs-on: self-hosted
    steps:
      # - name: Check PowerSell
      #   run: $PSVersionTable
      - name: Checkout
        uses: actions/checkout@v4

      # 버전 확인
      # - name: Check Node.js version
      #   run: node -v
      - name: npm install
        run: npm i